spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_db
    username: postgres
  jpa:
    hibernate.ddl-auto: validate
    # Custom validator can be loaded here
    # properties.hibernate.hbm2ddl.schema_filter_provider: wf.garnier. ...

# SQL logging
# logging.level.org.hibernate.SQL: DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
